api:
  dashboard: true
  insecure: false

entryPoints:
  notsecure:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web
          scheme: https
          permanent: true
  web:
    address: ':443'
    http:
      tls:
        certResolver: letsencrypt

certificatesResolvers:
  letsencrypt:
    acme:
      email: 'skeblow@gmail.com'
      storage: /letsencrypt/acme.json
      dnsChallenge:
        provider: cloudflare

providers:
  docker:
    endpoint: 'tcp://traefik-docker-socket-proxy:2375'
    exposedByDefault: false
